In [ ]:
import numpy as np 

def mask_3(n, s):
    mask_3 = np.triu(np.ones((n,n)), -s) - np.triu(np.ones((n,n)),s+1)
    return mask_3


mask_3 = mask_3(9,1)
mask_1 = mask_3[:,::-1]
print(mask_1,'\n', mask_3)




[[0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0.]] 
 [[1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [ ]:
import numpy as np

h1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
h2 = np.array([[0,0,0], [1,1,1], [0,0,0]])

print((np.stack((h1,h2), axis=2)).shape)

(3, 2, 3)


In [ ]:
import numpy as np
x = np.arange(5)
y = np.arange(6)
print(x)

NameError: name 'np' is not defined